replicaCount: 1
#github.com/ansible/awx-operator/config/default?ref=0.21.0
images:
  - name: quay.io/ansible/awx-operator
    tag:  2.19.0
service:
  enabled: true
  type: ClusterIP
  port: 3000

resources: {}