---
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-server
type: Opaque
data:
    # Default admin password hash (bcrypt recommended, or plain text if testing)
    #admin.password: {{ "admin" | b64enc | quote }}

# stringData:
    passowrd: "Start1234"
    username: "admin"