apiVersion: awx.ansible.com/v1beta1
kind: awx
metadata:
  name: awx
spec:
  admin_user: admin
  admin_paswwrd: awx-admin-Secret

  #enable ingress
  ingress_type: ingress 

hostanme: ansible.local

service_type: ClusterIP

#Ingress annotation for traefik (RKE2 default)
ingress_annotations:
  kubernetes.ioingress_class: traefik
  traefik.ingress.kubernetes.io/router.entrypoints: web

  postgres_storage_class: local-path
  postgres_data_volume_size: 5Gi